### ISSUE TITLE
Upload error - remote server returned 404

### ISSUE THREAD

**Issue by DrWhoCares** [Heroes-Profile/HeroesProfile.Uploader#35]
```
[2023-09-08 21:37:09.8875] WARN: Error uploading file 'C:\Users\Me\Documents\Heroes of the Storm\Accounts\1\1-Hero-1-1\Replays\Multiplayer\2023-09-08 21.37.09 Dragon Shire.StormReplay' System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Heroesprofile.Uploader.Common.Uploader.<Upload>d__6.MoveNext()
```
Happening since yesterday, for every single replay. Any match.

**Comment by Zemill** [comment]
We are migrating some services, so the uploading and parsing is currently off.  It is taking longer than anticpated
